### ISSUE TITLE
类型转换错误

### ISSUE THREAD

**Issue by jdhkai** [zhongjhATC/Retrofit2Rxjava2Download#1]
不知道作者有没有自己试过，在DownloadHandler中出现了一个很低级的错误。
![image](https://user-images.githubusercontent.com/5645783/50953381-252d2b80-14ee-11e9-9b82-78592d2e5b0d.png)
![image](https://user-images.githubusercontent.com/5645783/50953394-324a1a80-14ee-11e9-81b8-decf188d147b.png)
Progress添加到Bundle时用的是Float,获取的时候用int获取，直接报错了。

**Comment by zhongjhATC** [comment]
有试过，也应用上正式项目了，不过这个问题确实疏漏了，已修复。
